# Generated by Django 3.0.3 on 2020-02-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas_granada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='foto',
            field=models.FileField(blank=True, upload_to='fotos'),
        ),
    ]
